# Google Cloud Build script
steps:
# Run tests first
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
- name: 'gcr.io/cloud-builders/yarn'
  args: ['bootstrap']
- name: 'gcr.io/cloud-builders/yarn'
  args: ['test']
# Build container images afterwards
# Pull images for cache
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/alice-api-server:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/alice-qr-lib:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/magellan-models:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/medicine-frontend:latest']
# Actual build steps using cache
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-f', 'packages/alice-api-server/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/alice-api-server',
          '--cache-from', 'gcr.io/$PROJECT_ID/alice-api-server:latest',
          '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-f', 'packages/alice-qr-lib/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/alice-qr-lib',
          '--cache-from', 'gcr.io/$PROJECT_ID/alice-qr-lib:latest',
          '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-f', 'packages/magellan-models/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/magellan-models',
          '--cache-from', 'gcr.io/$PROJECT_ID/magellan-models:latest',
          '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-f', 'packages/medicine-frontend/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/medicine-frontend',
          '--cache-from', 'gcr.io/$PROJECT_ID/medicine-frontend:latest',
          '.' ]
# Push container images
images:
- 'gcr.io/$PROJECT_ID/alice-api-server'
- 'gcr.io/$PROJECT_ID/alice-qr-lib'
- 'gcr.io/$PROJECT_ID/magellan-models'
- 'gcr.io/$PROJECT_ID/medicine-frontend'


