timeout: 3600s
# Google Cloud Build script
steps:
# Run tests first
- id: pull_alice_sdk
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/alice-sdk']
- id: 'run_tests'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', 'gcr.io/$PROJECT_ID/alice-sdk',
          '--cache-from', 'gcr.io/$PROJECT_ID/alice-sdk',
          '.' ]
# Build container images afterwards
- id: pull_alice_api_server
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/alice-api-server']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['run_tests', 'pull_alice_api_server']
  args: [ 'build',
          '-f', 'packages/alice-api-server/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/alice-api-server',
          '--cache-from', 'gcr.io/$PROJECT_ID/alice-api-server',
          '.' ]

- id: pull_alice_qr_lib
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/alice-qr-lib']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['run_tests', 'pull_alice_qr_lib']
  args: [ 'build',
          '-f', 'packages/alice-qr-lib/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/alice-qr-lib',
          '--cache-from', 'gcr.io/$PROJECT_ID/alice-qr-lib',
          '.' ]

- id: pull_magellan_models
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/magellan-models']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['run_tests', 'pull_magellan_models']
  args: [ 'build',
          '-f', 'packages/magellan-models/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/magellan-models',
          '--cache-from', 'gcr.io/$PROJECT_ID/magellan-models',
          '.' ]

- id: pull_medicine_frontend_unminified
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/medicine-frontend-unminified']
  waitFor: ['-']
- id: build_medicine_frontend_unminified
  name: 'gcr.io/cloud-builders/docker'
  waitFor: ['run_tests', 'pull_medicine_frontend_unminified']
  args: [ 'build',
          '-f', 'packages/medicine-frontend/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/medicine-frontend-unminified',
          '--cache-from', 'gcr.io/$PROJECT_ID/medicine-frontend-unminified',
          '--target', 'node',
          '.' ]
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['run_tests', 'build_medicine_frontend_unminified']
  args: [ 'build',
          '-f', 'packages/medicine-frontend/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/medicine-frontend',
          '--cache-from', 'gcr.io/$PROJECT_ID/medicine-frontend-unminified',
          '.' ]

- id: pull_alice_worker_manager
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/alice-worker-manager']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['run_tests', 'pull_alice_worker_manager']
  args: [ 'build',
          '-f', 'packages/alice-worker-manager/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/alice-worker-manager',
          '--cache-from', 'gcr.io/$PROJECT_ID/alice-worker-manager',
          '.' ]

- id: pull_alice_mobile
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/alice-mobile']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['run_tests', 'pull_alice_mobile']
  args: [ 'build',
          '-e HOCKEY_APP_TOKEN',
          '-f', 'packages/alice-mobile/Dockerfile',
          '-t', 'gcr.io/$PROJECT_ID/alice-mobile',
          '--cache-from', 'gcr.io/$PROJECT_ID/alice-mobile',
          '.' ]
  secretEnv: ['HOCKEY_APP_TOKEN']

# Push container images
images:
- 'gcr.io/$PROJECT_ID/alice-sdk'
- 'gcr.io/$PROJECT_ID/alice-api-server'
- 'gcr.io/$PROJECT_ID/alice-qr-lib'
- 'gcr.io/$PROJECT_ID/alice-worker-manager'
- 'gcr.io/$PROJECT_ID/alice-mobile'
- 'gcr.io/$PROJECT_ID/magellan-models'
- 'gcr.io/$PROJECT_ID/medicine-frontend-unminified'
- 'gcr.io/$PROJECT_ID/medicine-frontend'

secrets:
- kmsKeyName: projects/alice-larp/locations/global/keyRings/cloudbuild/cryptoKeys/cloudbuild
  secretEnv:
    HOCKEY_APP_TOKEN: CiQAN/6WvJgdZnXKIm/oLJ/LqFnqlnTx1x9lUdIbPnSmthAAIv4SSQBrgk0K0MYRJL7i+zx9D/T4xRewJ0hX9uK4RAmxoEFSz8r/S/ZGdf6i+so+XbWOjXcUi902y1vULvHfzJPfBpOP3shE2WKXSXI=