apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alice-qr-lib
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - qr.alice.aerem.in
    secretName: tls-secret
  rules:
  - host: qr.alice.aerem.in
    http:
      paths:
      - path: /
        backend:
          serviceName: alice-qr-lib
          servicePort: 8159
