apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alice-api-server
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - api.alice.aerem.in
    secretName: tls-secret
  rules:
  - host: api.alice.aerem.in
    http:
      paths:
      - path: /
        backend:
          serviceName: alice-api-server
          servicePort: 8157
