apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - api.alice.aerem.in
    - qr.alice.aerem.in
    - couchdb.alice.aerem.in
    - elasticsearch.alice.aerem.in
    - kibana.alice.aerem.in
    - lab.alice.aerem.in
    secretName: tls-secret
  rules:
  - host: api.alice.aerem.in
    http:
      paths:
      - path: /*
        backend:
          serviceName: alice-api-server
          servicePort: 8157
  - host: qr.alice.aerem.in
    http:
      paths:
      - path: /*
        backend:
          serviceName: alice-qr-lib
          servicePort: 8159
  - host: couchdb.alice.aerem.in
    http:
      paths:
      - path: /*
        backend:
          serviceName: couchdb
          servicePort: 5984
  - host: elasticsearch.alice.aerem.in
    http:
      paths:
      - path: /*
        backend:
          serviceName: elasticsearch
          servicePort: 9200
  - host: kibana.alice.aerem.in
    http:
      paths:
      - path: /*
        backend:
          serviceName: kibana
          servicePort: 5601
  - host: lab.alice.aerem.in
    http:
      paths:
      - path: /*
        backend:
          serviceName: medicine-frontend
          servicePort: 8000