apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - elasticsearch.alice.aerem.in
    secretName: tls-secret
  rules:
  - host: elasticsearch.alice.aerem.in
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch
          servicePort: 9200
