apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alice-qr-lib
spec:
  selector:
    matchLabels:
      component: alice-qr-lib
  template:
    metadata:
      labels:
        component: alice-qr-lib
    spec:
      containers:
      - image: gcr.io/alice-larp/alice-qr-lib
        imagePullPolicy: Always
        name: alice-qr-lib
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 20
