apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alice-api-server
spec:
  selector:
    matchLabels:
      component: alice-api-server
  template:
    metadata:
      labels:
        component: alice-api-server
    spec:
      containers:
      - image: alicelarp/alice-api-server
        imagePullPolicy: Always
        name: alice-api-server
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: username
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: password
        - name: PUSH_SERVERKEY
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: push_serverkey
        ports:
        - containerPort: 8157
        readinessProbe:
          httpGet:
            path: /time
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /time
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 20
